node {
  def WORKSPACE = "/var/lib/jenkins/workspace/springboot-deploy"
  def dockerImageTag = "springboot-deploy${env.BUILD_NUMBER}"

  try{

     stage('Clone Repo'){
       git url: 'https://github.com/abhi2203/server-codebase-jenkis-docker.git',
           credentialsId: '836ffaf9-fc8a-4f98-bdd6-26c3f1083e9c',
           branch: 'master'
     }
     stage('Build docker'){
          dockerImage = docker.build("springboot-deploy${env.BUILD_NUMBER}")
     }
     stage('Deploy docker'){
           echo "Docker Image Tag Name: ${dockerImageTag}"
           sh "docker stop springboot-deploy || true && docker rm springboot-deploy || true"
           sh "docker run --name springboot-deploy -d -p 8070:8080 springboot-deploy${env.BUILD_NUMBER}"
     }

  }catch(e){
    throw e
  }
}