pipeline {
    agent { docker { image 'maven:3.8.4-openjdk-11-slim' } }
    stages {
      stage('Build') {
          steps {
             sh 'mvn --version'
             sh 'mvn clean install'
             archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
            }
        }
    }
}
